"""Plot widgets for live VisPy and offline Matplotlib views."""

from __future__ import annotations

import math
import os
import tempfile
from pathlib import Path

import numpy as np

if "MPLCONFIGDIR" not in os.environ:
    matplotlib_cache_dir = Path.home() / ".matplotlib"
    cache_target = matplotlib_cache_dir if matplotlib_cache_dir.exists() else matplotlib_cache_dir.parent
    if not os.access(cache_target, os.W_OK):
        os.environ["MPLCONFIGDIR"] = str(Path(tempfile.gettempdir()) / "matplotlib")

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PySide6.QtWidgets import QDialog, QVBoxLayout, QWidget
from vispy import scene
from vispy.color import get_colormap


class VisPySignalPlot(QWidget):
    """Live VisPy plot with manual axes, labels, and all-channel mode.

    VisPy can draw axes with `AxisWidget`, but the final-project exercise asks
    for a clear rolling time plot. This widget therefore draws its own axis
    lines, ticks, and text labels so we can control exactly where the signal
    begins and how the time labels move.
    """

    def __init__(self, title: str, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.title = title
        self.sample_rate = 1000.0
        self.visible_duration_seconds = 10.0
        self.time_tick_step = 2.0
        self.y_scale = 1.0
        self.current_signal_time = 0.0
        self.lines: list[object] = []
        self.channel_labels: list[scene.Text] = []

        # The outer Qt layout only hosts the native OpenGL widget generated by
        # VisPy. Everything inside the plot is drawn in the VisPy scene graph.
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # `dpi=96` avoids a macOS/offscreen VisPy DPI lookup crash while still
        # rendering normally when the app is launched with a real display.
        self.canvas = scene.SceneCanvas(
            keys="interactive",
            show=False,
            bgcolor="#ffffff",
            size=(1000, 600),
            dpi=96,
        )
        self.canvas.native.setMinimumHeight(380)
        layout.addWidget(self.canvas.native)

        self.view = self.canvas.central_widget.add_view()
        self.view.camera = "panzoom"

        # Manual plot primitives. They are kept as persistent objects and only
        # their data is updated on each frame, which is much faster than
        # recreating visual objects every timer tick.
        self.x_axis_line = scene.visuals.Line(parent=self.view.scene, color="black", width=1)
        self.y_axis_line = scene.visuals.Line(parent=self.view.scene, color="black", width=1)
        self.tick_line = scene.visuals.Line(
            parent=self.view.scene,
            color="black",
            width=1,
            connect="segments",
        )
        self.zero_line = scene.visuals.Line(
            parent=self.view.scene,
            color=(0.65, 0.65, 0.65, 1.0),
            width=1,
        )
        self.title_text = scene.Text(
            text=title,
            color="#202124",
            font_size=12,
            anchor_x="left",
            anchor_y="top",
            parent=self.view.scene,
        )
        self.y_axis_label = scene.Text(
            text="Amplitude",
            color="#202124",
            font_size=10,
            anchor_x="center",
            anchor_y="center",
            parent=self.view.scene,
        )
        self.x_axis_label = scene.Text(
            text="Time (s)",
            color="#202124",
            font_size=10,
            anchor_x="center",
            anchor_y="top",
            parent=self.view.scene,
        )

        # Pre-create a fixed pool of tick labels. During updates we move and
        # hide/show them instead of allocating new Text objects.
        self.time_texts = [
            scene.Text(
                text="",
                color="#202124",
                font_size=10,
                anchor_x="center",
                anchor_y="top",
                parent=self.view.scene,
            )
            for _ in range(10)
        ]

        self._ensure_line_count(1)
        self._update_axes()
        self._update_time_ticks()
        self._update_camera()

    def plot_single_channel(
        self,
        data: np.ndarray,
        current_time_seconds: float | None = None,
        channel_number: int | None = None,
        mode: str = "Original",
    ) -> None:
        """Draw one selected channel in a fixed-width moving time window.

        The important display rule is: whatever data is currently available is
        anchored at x=0, the y-axis. Once the live buffer reaches the full
        visible duration, the newest ten seconds are shown. This avoids the
        confusing empty-left/empty-right canvas that happens when a short buffer
        is drawn at the far right of a longer time window.
        """
        self._hide_channel_labels()
        if current_time_seconds is not None:
            self.current_signal_time = float(current_time_seconds)
        elif data.size > 0:
            self.current_signal_time = data.size / self.sample_rate

        self._ensure_line_count(1)
        if channel_number is not None:
            self.title_text.text = f"Channel {channel_number} - {mode}"
        else:
            self.title_text.text = f"{self.title} - {mode}"

        for extra_line in self.lines[1:]:
            extra_line.set_data(pos=np.empty((0, 2), dtype=np.float32))

        data = np.asarray(data, dtype=np.float64)
        if data.size < 2:
            self.lines[0].set_data(pos=np.empty((0, 2), dtype=np.float32))
            self._update_axes()
            self._update_time_ticks()
            self._update_camera()
            return

        self.y_scale = self._robust_y_scale(data)
        max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
        visible_data = data[-max_visible_samples:]

        # Left-align the plotted samples at the y-axis. The labels still show
        # absolute stream time by using `current_signal_time` below.
        display_x = np.arange(visible_data.size, dtype=np.float64) / self.sample_rate

        if display_x.size < 2:
            self.lines[0].set_data(pos=np.empty((0, 2), dtype=np.float32))
        else:
            points = np.column_stack((display_x, visible_data))
            self.lines[0].set_data(
                pos=points,
                color=(0.05, 0.30, 0.72, 1.0),
                width=2.0,
            )

        self._update_axes()
        self._update_time_ticks()
        self._update_camera()

    def plot_all_channels(self, data: np.ndarray, current_time_seconds: float | None = None) -> None:
        """Draw all channels with normalized amplitude and vertical offsets.

        Each channel is centered by its median and scaled by its 95th
        percentile amplitude so one noisy/high-amplitude channel does not hide
        the rest of the overview.
        """
        data = np.asarray(data, dtype=np.float64)
        channel_count = data.shape[0] if data.ndim == 2 else 0
        self._ensure_line_count(channel_count)
        self._ensure_channel_labels(channel_count)

        if current_time_seconds is not None:
            self.current_signal_time = float(current_time_seconds)
        elif data.size > 0:
            self.current_signal_time = data.shape[1] / self.sample_rate

        if data.size == 0 or channel_count == 0:
            for line in self.lines:
                line.set_data(pos=np.empty((0, 2), dtype=np.float32))
            self._hide_channel_labels()
            self.view.camera.set_range(x=(0, 1), y=(-1, 1), margin=0.05)
            return

        max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
        visible_data = data[:, -max_visible_samples:]
        display_x = np.arange(visible_data.shape[1], dtype=np.float64) / self.sample_rate
        colors = get_colormap("viridis").map(np.linspace(0.05, 0.95, channel_count))
        offsets = np.arange(channel_count, 0, -1, dtype=np.float64) * 2.5

        for channel_index in range(channel_count):
            row = visible_data[channel_index]
            centered = row - np.nanmedian(row)
            scale = np.nanpercentile(np.abs(centered), 95)
            if not np.isfinite(scale) or scale <= 0:
                scale = 1.0
            y_values = centered / scale + offsets[channel_index]
            points = np.column_stack((display_x, y_values))
            self.lines[channel_index].set_data(
                pos=points,
                color=colors[channel_index],
                width=1.1,
            )

            label = self.channel_labels[channel_index]
            label.text = f"Ch {channel_index + 1}"
            label.pos = (-0.35, offsets[channel_index])
            label.visible = True

        for extra_line in self.lines[channel_count:]:
            extra_line.set_data(pos=np.empty((0, 2), dtype=np.float32))

        self._set_all_channel_axes(offsets[0] + 1.5)

    def _set_all_channel_axes(self, y_max: float) -> None:
        y_min = 0.0
        self.x_axis_line.set_data(
            pos=np.array([[0.0, y_min], [self.visible_duration_seconds, y_min]], dtype=float)
        )
        self.y_axis_line.set_data(pos=np.array([[0.0, y_min], [0.0, y_max]], dtype=float))
        self.zero_line.set_data(pos=np.empty((0, 2), dtype=np.float32))
        self.title_text.pos = (0.15, y_max)
        self.y_axis_label.text = "Channels"
        self.y_axis_label.pos = (-0.55, y_max * 0.5)
        self.x_axis_label.pos = (self.visible_duration_seconds * 0.5, y_min - 2.75)
        self._update_time_ticks(y_min=y_min, label_y=y_min - 2.2)
        self.view.camera.set_range(
            x=(-0.75, self.visible_duration_seconds),
            y=(y_min - 3.0, y_max + 1.0),
            margin=0.02,
        )

    def _update_axes(self) -> None:
        y_min = -self.y_scale
        y_max = self.y_scale
        self.x_axis_line.set_data(
            pos=np.array([[0.0, y_min], [self.visible_duration_seconds, y_min]], dtype=float)
        )
        self.y_axis_line.set_data(pos=np.array([[0.0, y_min], [0.0, y_max]], dtype=float))
        self.zero_line.set_data(
            pos=np.array([[0.0, 0.0], [self.visible_duration_seconds, 0.0]], dtype=float)
        )
        self.title_text.pos = (0.15, y_max)
        self.y_axis_label.text = "Amplitude"
        self.y_axis_label.pos = (-0.62, 0.0)
        self.x_axis_label.pos = (self.visible_duration_seconds * 0.5, y_min - 0.25 * (2 * self.y_scale))

    def _update_time_ticks(self, y_min: float | None = None, label_y: float | None = None) -> None:
        """Move x-axis ticks and labels for the current visible time range."""
        if y_min is None:
            y_min = -self.y_scale
        if label_y is None:
            label_y = y_min - 0.12 * (2 * self.y_scale)

        tick_height = max(0.05, 0.05 * (2 * self.y_scale))
        # When less than one full window has arrived, the displayed signal
        # starts at time 0 on the y-axis. After the buffer is full, the displayed
        # labels show the rolling absolute stream time.
        visible_end_time = max(self.visible_duration_seconds, self.current_signal_time)
        visible_start_time = visible_end_time - self.visible_duration_seconds
        first_tick = math.floor(visible_start_time / self.time_tick_step) * self.time_tick_step

        tick_values = []
        tick_time = first_tick
        while tick_time <= visible_end_time + self.time_tick_step:
            display_x = tick_time - visible_start_time
            if tick_time >= 0.0 and 0.0 <= display_x <= self.visible_duration_seconds:
                tick_values.append((tick_time, display_x))
            tick_time += self.time_tick_step

        tick_positions = []
        for _tick_time, display_x in tick_values:
            tick_positions.append([display_x, y_min])
            tick_positions.append([display_x, y_min + tick_height])

        self.tick_line.set_data(
            pos=np.asarray(tick_positions, dtype=float)
            if tick_positions
            else np.empty((0, 2), dtype=float)
        )

        for index, text in enumerate(self.time_texts):
            if index < len(tick_values):
                tick_time, display_x = tick_values[index]
                text.text = f"{tick_time:.0f}s"
                text.pos = (display_x, label_y)
                text.visible = True
            else:
                text.visible = False

    def _update_camera(self) -> None:
        """Keep axes, labels, and the signal framed inside the canvas."""
        label_space = 0.18 * (2 * self.y_scale)
        self.view.camera.set_range(
            x=(-0.85, self.visible_duration_seconds),
            y=(-self.y_scale - label_space, self.y_scale * 1.08),
            margin=0.02,
        )

    def _robust_y_scale(self, data: np.ndarray) -> float:
        """Estimate a stable y range without being dominated by outliers."""
        finite = data[np.isfinite(data)]
        if finite.size == 0:
            return 1.0
        centered = finite - np.nanmedian(finite)
        scale = np.nanpercentile(np.abs(centered), 98) * 1.3
        if not np.isfinite(scale) or scale <= 0:
            scale = max(1.0, float(np.nanmax(np.abs(finite))))
        return max(scale, 1e-6)

    def _ensure_line_count(self, count: int) -> None:
        """Ensure enough persistent line visuals exist for the requested plot."""
        while len(self.lines) < count:
            self.lines.append(scene.visuals.Line(parent=self.view.scene))

    def _ensure_channel_labels(self, count: int) -> None:
        """Ensure all-channel mode has one text label per channel."""
        while len(self.channel_labels) < count:
            self.channel_labels.append(
                scene.Text(
                    text="",
                    color="#202124",
                    font_size=8,
                    anchor_x="right",
                    anchor_y="center",
                    parent=self.view.scene,
                )
            )
        for label in self.channel_labels[count:]:
            label.visible = False

    def _hide_channel_labels(self) -> None:
        for label in self.channel_labels:
            label.visible = False


class AllChannelsDialog(QDialog):
    """Dialog showing the live all-channel overview."""

    def __init__(self, plot: VisPySignalPlot, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setWindowTitle("Plot All Channels")
        self.resize(1100, 760)
        layout = QVBoxLayout(self)
        layout.addWidget(plot)


class OfflineMatplotlibPlot(QWidget):
    """Offline Matplotlib plot for the recorded selected channel."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.sample_rate = 1000.0
        self.selected_channel = 0

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        self.figure = Figure(figsize=(7, 4), tight_layout=True)
        self.canvas = FigureCanvas(self.figure)
        self.axes = self.figure.add_subplot(111)
        layout.addWidget(self.canvas)
        self.show_empty("No recorded data yet.")

    def set_channel(self, channel_index: int) -> None:
        self.selected_channel = channel_index

    def plot(self, data: np.ndarray, mode: str) -> None:
        if data.size == 0 or data.shape[1] == 0:
            self.show_empty("No recorded data available.")
            return

        channel = min(self.selected_channel, data.shape[0] - 1)
        y_values = data[channel]
        x_values = np.arange(y_values.size, dtype=np.float64) / self.sample_rate

        self.axes.clear()
        self.axes.plot(x_values, y_values, color="#0d5aa7", linewidth=1.0)
        self.axes.set_title(f"Channel {channel + 1} - {mode}")
        self.axes.set_xlabel("Time (s)")
        self.axes.set_ylabel("Amplitude")
        self.axes.grid(True, alpha=0.25)
        self.canvas.draw_idle()

    def show_empty(self, message: str) -> None:
        self.axes.clear()
        self.axes.text(0.5, 0.5, message, ha="center", va="center")
        self.axes.set_axis_off()
        self.canvas.draw_idle()
