"""Plot widgets for live VisPy and offline Matplotlib views."""

from __future__ import annotations

import math
import os
import tempfile
from pathlib import Path

import numpy as np

if "MPLCONFIGDIR" not in os.environ:
    matplotlib_cache_dir = Path.home() / ".matplotlib"
    cache_target = matplotlib_cache_dir if matplotlib_cache_dir.exists() else matplotlib_cache_dir.parent
    if not os.access(cache_target, os.W_OK):
        os.environ["MPLCONFIGDIR"] = str(Path(tempfile.gettempdir()) / "matplotlib")

from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PySide6.QtWidgets import QDialog, QVBoxLayout, QWidget
from vispy import scene

try:
    from . import button_labels
except ImportError:
    from views import button_labels


EMPTY_LINE_POINTS = np.array([[0.0, 0.0], [0.0, 0.0]], dtype=np.float32)
CHANNEL_COLORS = [
    "#006D77",
    "#00A6A6",
    "#008C8C",
    "#0096C7",
    "#0077B6",
    "#3A86FF",
    "#4361EE",
    "#5E60CE",
    "#7B2CBF",
    "#9D4EDD",
    "#C2185B",
    "#D81B60",
    "#EC407A",
    "#F06292",
    "#AD1457",
    "#880E4F",
    "#C1121F",
    "#D62828",
    "#E76F51",
    "#F77F00",
    "#FF9F1C",
    "#D4A017",
    "#7CB518",
    "#55A630",
    "#2D6A4F",
    "#1B4332",
    "#52B788",
    "#40916C",
    "#577590",
    "#4D648D",
    "#6A4C93",
    "#8338EC",
]


def channel_color_rgba(channel_index: int, channel_count: int = 32) -> tuple[float, float, float, float]:
    """Return the stable display color for a zero-based channel index."""
    del channel_count
    hex_color = CHANNEL_COLORS[channel_index % len(CHANNEL_COLORS)].lstrip("#")
    red = int(hex_color[0:2], 16) / 255.0
    green = int(hex_color[2:4], 16) / 255.0
    blue = int(hex_color[4:6], 16) / 255.0
    return (red, green, blue, 1.0)


def channel_color_css(channel_index: int, channel_count: int = 32) -> str:
    """Return the stable display color as a Qt stylesheet rgb() string."""
    del channel_count
    return CHANNEL_COLORS[channel_index % len(CHANNEL_COLORS)]


def channel_color_rgba_css(channel_index: int, alpha: float, channel_count: int = 32) -> str:
    """Return the stable display color as a Qt stylesheet rgba() string."""
    red, green, blue, _alpha = channel_color_rgba(channel_index, channel_count)
    return f"rgba({round(red * 255)}, {round(green * 255)}, {round(blue * 255)}, {alpha:.2f})"


class VisPySignalPlot(QWidget):
    """Live VisPy plot with manual axes, labels, and all-channel mode.

    VisPy can draw axes with `AxisWidget`, but the final-project exercise asks
    for a clear rolling time plot. This widget therefore draws its own axis
    lines, ticks, and text labels so we can control exactly where the signal
    begins and how the time labels move.
    """

    def __init__(self, title: str, parent: QWidget | None = None) -> None:
        """Create the VisPy scene used by MainView's live and all-channel plots."""
        super().__init__(parent)
        self.title = title
        self.sample_rate = 1000.0
        self.visible_duration_seconds = 10.0
        self.time_tick_step = 2.0
        self.default_y_scale = 2000.0
        self.y_scale = self.default_y_scale
        self.current_signal_time = 0.0
        self.visible_channel_limit: int | None = 4
        self.minimum_plot_height = 380
        self.viewport_height = self.minimum_plot_height
        self._plotted_channel_count = 0
        self.left_margin_fraction = 0.18
        self.lines: list[object] = []
        self.channel_labels: list[scene.Text] = []
        self._single_scale_context: tuple[int | None, str] | None = None
        self._all_channel_scales = np.empty(0, dtype=np.float64)
        self._all_scale_mode: str | None = None

        # The outer Qt layout only hosts the native OpenGL widget generated by
        # VisPy. Everything inside the plot is drawn in the VisPy scene graph.
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # `dpi=96` avoids a macOS/offscreen VisPy DPI lookup crash while still
        # rendering normally when the app is launched with a real display.
        self.canvas = scene.SceneCanvas(
            keys="interactive",
            show=False,
            bgcolor="#ffffff",
            size=(1000, 600),
            dpi=96,
        )
        self.canvas.native.setMinimumHeight(self.minimum_plot_height)
        layout.addWidget(self.canvas.native)

        self.view = self.canvas.central_widget.add_view()
        self.view.camera = scene.PanZoomCamera(interactive=False)

        # Manual plot primitives. They are kept as persistent objects and only
        # their data is updated on each frame, which is much faster than
        # recreating visual objects every timer tick.
        self.x_axis_line = scene.visuals.Line(parent=self.view.scene, color="black", width=1)
        self.y_axis_line = scene.visuals.Line(parent=self.view.scene, color="black", width=1)
        self.tick_line = scene.visuals.Line(
            parent=self.view.scene,
            color="black",
            width=1,
            connect="segments",
        )
        self.y_tick_line = scene.visuals.Line(
            parent=self.view.scene,
            color="black",
            width=1,
            connect="segments",
        )
        self.zero_line = scene.visuals.Line(
            parent=self.view.scene,
            color=(0.65, 0.65, 0.65, 1.0),
            width=1,
        )
        self.title_text = scene.Text(
            text=title,
            color="#202124",
            font_size=12,
            anchor_x="center",
            anchor_y="top",
            parent=self.view.scene,
        )
        self.y_axis_label = scene.Text(
            text="Amplitude (µV)",
            color="#202124",
            font_size=10,
            anchor_x="center",
            anchor_y="center",
            parent=self.view.scene,
            rotation=-90,
        )
        self.x_axis_label = scene.Text(
            text="Time (s)",
            color="#202124",
            font_size=10,
            anchor_x="center",
            anchor_y="top",
            parent=self.view.scene,
        )

        # Pre-create a fixed pool of tick labels. During updates we move and
        # hide/show them instead of allocating new Text objects.
        self.time_texts: list[scene.Text] = []
        self.y_tick_texts: list[scene.Text] = []

        self._ensure_line_count(1)
        self._update_axes()
        self._update_time_ticks()
        self._update_camera()

    def set_visible_channel_limit(self, limit: int | None) -> None:
        """Set how many stacked channels should fit before the plot scrolls."""
        self.visible_channel_limit = limit
        self._update_minimum_height(self._plotted_channel_count)

    def set_visible_duration_seconds(self, seconds: float | None) -> None:
        """Set the rolling time span shown on the x-axis."""
        if seconds is None:
            return
        self.visible_duration_seconds = max(0.5, float(seconds))
        self._update_time_ticks()
        self._update_camera()

    def set_visible_channel_viewport_height(self, height: int) -> None:
        """Use the scroll viewport height to keep the chosen number visible."""
        self.viewport_height = max(self.minimum_plot_height, int(height))
        self._update_minimum_height(self._plotted_channel_count)

    def plot_single_channel(
        self,
        data: np.ndarray,
        current_time_seconds: float | None = None,
        channel_number: int | None = None,
        mode: str = "Original",
    ) -> None:
        """Draw one selected channel in a fixed-width moving time window.

        The important display rule is: whatever data is currently available is
        anchored at x=0, the y-axis. Once the live buffer reaches the full
        visible duration, the newest ten seconds are shown. This avoids the
        confusing empty-left/empty-right canvas that happens when a short buffer
        is drawn at the far right of a longer time window.
        """
        self._hide_channel_labels()
        if current_time_seconds is not None:
            self.current_signal_time = float(current_time_seconds)
        elif data.size > 0:
            self.current_signal_time = data.size / self.sample_rate

        self._ensure_line_count(1)
        if channel_number is not None:
            self.title_text.text = f"Channel {channel_number} - {mode}"
        else:
            self.title_text.text = f"{self.title} - {mode}"

        for extra_line in self.lines[1:]:
            self._clear_line(extra_line)

        data = np.asarray(data, dtype=np.float64)
        if data.size < 2:
            self._clear_line(self.lines[0])
            self._update_axes()
            self._update_time_ticks()
            self._update_camera()
            return

        self._update_single_channel_scale(data, channel_number, mode)
        max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
        visible_data = data[-max_visible_samples:]

        # Left-align the plotted samples at the y-axis. The labels still show
        # absolute stream time by using `current_signal_time` below.
        display_x = np.arange(visible_data.size, dtype=np.float64) / self.sample_rate

        if display_x.size < 2:
            self._clear_line(self.lines[0])
        else:
            points = np.column_stack((display_x, visible_data))
            self.lines[0].set_data(
                pos=points,
                color=(0.05, 0.30, 0.72, 1.0),
                width=2.0,
            )

        self._update_axes()
        self._update_time_ticks()
        self._update_camera()

    def plot_selected_channels(
        self,
        data: np.ndarray,
        channel_indices: list[int],
        current_time_seconds: float | None = None,
        mode: str = "Original",
    ) -> None:
        """Draw selected channels as stacked, individually scaled rows."""
        data = np.asarray(data, dtype=np.float64)
        valid_indices = [
            channel_index
            for channel_index in channel_indices
            if data.ndim == 2 and 0 <= channel_index < data.shape[0]
        ]
        self._plotted_channel_count = len(valid_indices)
        self._update_minimum_height(len(valid_indices))
        self._ensure_line_count(len(valid_indices))
        self._ensure_channel_labels(len(valid_indices))
        self._ensure_all_channel_scales(data.shape[0] if data.ndim == 2 else 0, mode)

        if current_time_seconds is not None:
            self.current_signal_time = float(current_time_seconds)
        elif data.size > 0 and data.ndim == 2:
            self.current_signal_time = data.shape[1] / self.sample_rate

        if data.size == 0 or data.ndim != 2 or data.shape[1] == 0 or not valid_indices:
            for line in self.lines:
                self._clear_line(line)
            self._hide_channel_labels()
            self.title_text.text = "Selected Channels: none"
            self.y_scale = self.default_y_scale
            self._single_scale_context = None
            self._update_axes()
            self._update_time_ticks()
            self._update_camera()
            return

        self.title_text.text = self._selected_channels_title(valid_indices)
        max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
        visible_data = data[:, -max_visible_samples:]
        display_x = np.arange(visible_data.shape[1], dtype=np.float64) / self.sample_rate
        row_spacing = 3.0
        offsets = np.arange(len(valid_indices) - 1, -1, -1, dtype=np.float64) * row_spacing
        y_tick_values: list[tuple[float, str]] = []

        for row_index, channel_index in enumerate(valid_indices):
            row = visible_data[channel_index]
            centered = row - np.nanmedian(row)
            scale = self.default_y_scale
            y_values = centered / scale + offsets[row_index]
            points = np.column_stack((display_x, y_values))
            self.lines[row_index].set_data(
                pos=points,
                color=channel_color_rgba(channel_index, data.shape[0]),
                width=1.5,
            )

            label = self.channel_labels[row_index]
            label.text = f"Ch {channel_index + 1:02d}"
            label.color = channel_color_rgba(channel_index, data.shape[0])
            label.pos = (self._channel_label_x(), offsets[row_index])
            label.visible = True

            y_tick_values.extend(
                [
                    (offsets[row_index] - 1.0, self._format_amplitude(-scale)),
                    (offsets[row_index] + 1.0, self._format_amplitude(scale)),
                ]
            )

        for extra_line in self.lines[len(valid_indices) :]:
            self._clear_line(extra_line)

        y_min = float(offsets[-1] - 1.35)
        y_max = float(offsets[0] + 1.35)
        self._set_stacked_channel_axes(y_min, y_max, y_tick_values)

    def plot_all_channels(
        self,
        data: np.ndarray,
        current_time_seconds: float | None = None,
        mode: str = "Original",
    ) -> None:
        """Draw all channels with normalized amplitude and vertical offsets.

        Each channel is centered by its median and scaled by its 95th
        percentile amplitude so one noisy/high-amplitude channel does not hide
        the rest of the overview.
        """
        data = np.asarray(data, dtype=np.float64)
        channel_count = data.shape[0] if data.ndim == 2 else 0
        self._ensure_line_count(channel_count)
        self._ensure_channel_labels(channel_count)
        self._ensure_all_channel_scales(channel_count, mode)

        if current_time_seconds is not None:
            self.current_signal_time = float(current_time_seconds)
        elif data.size > 0:
            self.current_signal_time = data.shape[1] / self.sample_rate

        if data.size == 0 or channel_count == 0:
            for line in self.lines:
                self._clear_line(line)
            self._hide_channel_labels()
            self.view.camera.set_range(x=(0, 1), y=(-1, 1), margin=0.05)
            return

        max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
        visible_data = data[:, -max_visible_samples:]
        display_x = np.arange(visible_data.shape[1], dtype=np.float64) / self.sample_rate
        offsets = np.arange(channel_count, 0, -1, dtype=np.float64) * 2.5

        for channel_index in range(channel_count):
            row = visible_data[channel_index]
            centered = row - np.nanmedian(row)
            scale = self._stable_all_channel_scale(channel_index, centered)
            y_values = centered / scale + offsets[channel_index]
            points = np.column_stack((display_x, y_values))
            self.lines[channel_index].set_data(
                pos=points,
                color=channel_color_rgba(channel_index, channel_count),
                width=1.1,
            )

            label = self.channel_labels[channel_index]
            label.text = f"Ch {channel_index + 1}"
            label.pos = (self._channel_label_x(), offsets[channel_index])
            label.visible = True

        for extra_line in self.lines[channel_count:]:
            self._clear_line(extra_line)

        self._set_all_channel_axes(offsets[0] + 1.5)

    def _set_all_channel_axes(self, y_max: float) -> None:
        y_min = 0.0
        self.x_axis_line.set_data(
            pos=np.array([[0.0, y_min], [self.visible_duration_seconds, y_min]], dtype=float)
        )
        self.y_axis_line.set_data(pos=np.array([[0.0, y_min], [0.0, y_max]], dtype=float))
        self._clear_line(self.zero_line)
        self._clear_line(self.y_tick_line)
        self._hide_y_tick_labels()
        self.title_text.pos = (self.visible_duration_seconds * 0.5, y_max)
        self.y_axis_label.text = "Channels"
        self.y_axis_label.rotation = 0
        self.y_axis_label.pos = (self._y_axis_label_x(), y_max * 0.5)
        self.x_axis_label.pos = (self.visible_duration_seconds * 0.5, y_min - 2.75)
        self._update_time_ticks(y_min=y_min, label_y=y_min - 2.2)
        self.view.camera.set_range(
            x=(self._plot_x_min(), self.visible_duration_seconds),
            y=(y_min - 3.0, y_max + 1.0),
            margin=0.02,
        )

    def _set_stacked_channel_axes(
        self,
        y_min: float,
        y_max: float,
        y_tick_values: list[tuple[float, str]],
    ) -> None:
        self.x_axis_line.set_data(
            pos=np.array([[0.0, y_min], [self.visible_duration_seconds, y_min]], dtype=float)
        )
        self.y_axis_line.set_data(pos=np.array([[0.0, y_min], [0.0, y_max]], dtype=float))
        self._clear_line(self.zero_line)
        self.title_text.pos = (self.visible_duration_seconds * 0.5, y_max)
        self.y_axis_label.text = "Amplitude (µV)"
        self.y_axis_label.rotation = -90
        self.y_axis_label.pos = (self._y_axis_label_x(), (y_min + y_max) * 0.5)
        time_label_y, axis_label_y = self._below_x_axis_positions(y_min, y_max)
        self.x_axis_label.pos = (self.visible_duration_seconds * 0.5, axis_label_y)
        self._update_y_ticks(y_tick_values)
        self._update_time_ticks(y_min=y_min, label_y=time_label_y)
        self.view.camera.set_range(
            x=(self._plot_x_min(), self.visible_duration_seconds),
            y=(axis_label_y - self._bottom_padding(y_min, y_max), y_max + 0.35),
            margin=0.02,
        )

    def _update_axes(self) -> None:
        y_min = -self.y_scale
        y_max = self.y_scale
        self.x_axis_line.set_data(
            pos=np.array([[0.0, y_min], [self.visible_duration_seconds, y_min]], dtype=float)
        )
        self.y_axis_line.set_data(pos=np.array([[0.0, y_min], [0.0, y_max]], dtype=float))
        self.zero_line.set_data(
            pos=np.array([[0.0, 0.0], [self.visible_duration_seconds, 0.0]], dtype=float),
            color=(0.65, 0.65, 0.65, 1.0),
            width=1,
        )
        self.title_text.pos = (self.visible_duration_seconds * 0.5, y_max)
        self.y_axis_label.text = "Amplitude (µV)"
        self.y_axis_label.rotation = -90
        self.y_axis_label.pos = (self._y_axis_label_x(), 0.0)
        self.x_axis_label.pos = (self.visible_duration_seconds * 0.5, y_min - 0.25 * (2 * self.y_scale))
        y_ticks = self._single_channel_y_ticks()
        self._update_y_ticks(y_ticks)

    def _update_single_channel_scale(
        self,
        data: np.ndarray,
        channel_number: int | None,
        mode: str,
    ) -> None:
        """Keep the live y-axis from shrinking and magnifying old samples."""
        context = (channel_number, mode)
        candidate_scale = self._robust_y_scale(data)
        if self._single_scale_context != context:
            self.y_scale = candidate_scale
            self._single_scale_context = context
            return
        self.y_scale = max(self.y_scale, candidate_scale)

    def _ensure_all_channel_scales(self, channel_count: int, mode: str) -> None:
        """Reset all-channel normalization only when the plotted signal changes."""
        if self._all_scale_mode != mode or self._all_channel_scales.size != channel_count:
            self._all_channel_scales = np.zeros(channel_count, dtype=np.float64)
            self._all_scale_mode = mode

    def _stable_all_channel_scale(self, channel_index: int, centered: np.ndarray) -> float:
        """Return a per-channel scale that can expand but not shrink on refresh."""
        candidate_scale = np.nanpercentile(np.abs(centered), 95)
        if not np.isfinite(candidate_scale) or candidate_scale <= 0:
            candidate_scale = 1.0
        previous_scale = self._all_channel_scales[channel_index]
        if np.isfinite(previous_scale) and previous_scale > 0:
            candidate_scale = max(previous_scale, candidate_scale)
        self._all_channel_scales[channel_index] = candidate_scale
        return self._all_channel_scales[channel_index]

    def _update_time_ticks(self, y_min: float | None = None, label_y: float | None = None) -> None:
        """Move x-axis ticks and labels for the current visible time range."""
        if y_min is None:
            y_min = -self.y_scale
        if label_y is None:
            label_y = y_min - 0.12 * (2 * self.y_scale)

        # When less than one full window has arrived, the displayed signal
        # starts at time 0 on the y-axis. After the buffer is full, the displayed
        # labels show the rolling absolute stream time.
        visible_end_time = max(self.visible_duration_seconds, self.current_signal_time)
        visible_start_time = visible_end_time - self.visible_duration_seconds
        tick_step = self._adaptive_time_tick_step()
        first_tick = math.floor(visible_start_time / tick_step) * tick_step

        tick_values = []
        tick_time = first_tick
        while tick_time <= visible_end_time + tick_step:
            display_x = tick_time - visible_start_time
            if tick_time >= 0.0 and 0.0 <= display_x <= self.visible_duration_seconds:
                tick_values.append((tick_time, display_x))
            tick_time += tick_step

        self._clear_line(self.tick_line)
        self._ensure_time_label_count(len(tick_values))

        for index, text in enumerate(self.time_texts):
            if index < len(tick_values):
                tick_time, display_x = tick_values[index]
                text.text = f"{tick_time:.0f}s"
                text.pos = (display_x, label_y)
                text.visible = True
            else:
                text.visible = False

    def _update_y_ticks(self, tick_values: list[tuple[float, str]]) -> None:
        """Move y-axis ticks and labels for amplitude read-off."""
        self._clear_line(self.y_tick_line)

        self._ensure_y_tick_label_count(len(tick_values))
        for index, text in enumerate(self.y_tick_texts):
            if index < len(tick_values):
                y_value, label = tick_values[index]
                text.text = label
                text.pos = (self._y_tick_label_x(), y_value)
                text.visible = True
            else:
                text.visible = False

    def _single_channel_y_ticks(self) -> list[tuple[float, str]]:
        """Return readable amplitude ticks for the current single-channel scale."""
        return [
            (-self.y_scale, self._format_amplitude(-self.y_scale)),
            (-self.y_scale * 0.5, self._format_amplitude(-self.y_scale * 0.5)),
            (self.y_scale * 0.5, self._format_amplitude(self.y_scale * 0.5)),
            (self.y_scale, self._format_amplitude(self.y_scale)),
        ]

    def _selected_channels_title(self, channel_indices: list[int]) -> str:
        """Format selected channels as compact one-based ranges."""
        if not channel_indices:
            return "Selected Channels: none"

        sorted_channels = sorted(set(channel_indices))
        ranges: list[tuple[int, int]] = []
        start = sorted_channels[0]
        end = start
        for channel_index in sorted_channels[1:]:
            if channel_index == end + 1:
                end = channel_index
            else:
                ranges.append((start, end))
                start = channel_index
                end = channel_index
        ranges.append((start, end))

        parts = []
        for start, end in ranges:
            if start == end:
                parts.append(f"Ch {start + 1:02d}")
            else:
                parts.append(f"Ch {start + 1:02d} - Ch {end + 1:02d}")
        return f"Selected Channels: {', '.join(parts)}"

    def _ensure_y_tick_label_count(self, count: int) -> None:
        while len(self.y_tick_texts) < count:
            self.y_tick_texts.append(
                scene.Text(
                    text="",
                    color="#202124",
                    font_size=8,
                    anchor_x="right",
                    anchor_y="center",
                    parent=self.view.scene,
                )
            )

    def _hide_y_tick_labels(self) -> None:
        self._clear_line(self.y_tick_line)
        for text in self.y_tick_texts:
            text.visible = False

    def _format_amplitude(self, value: float) -> str:
        absolute = abs(value)
        if absolute >= 100:
            return f"{value:.0f}"
        if absolute >= 10:
            return f"{value:.1f}"
        return f"{value:.2f}"

    def _update_camera(self) -> None:
        """Keep axes, labels, and the signal framed inside the canvas."""
        label_space = 0.18 * (2 * self.y_scale)
        self.view.camera.set_range(
            x=(self._plot_x_min(), self.visible_duration_seconds),
            y=(-self.y_scale - label_space, self.y_scale * 1.08),
            margin=0.02,
        )

    def _robust_y_scale(self, data: np.ndarray) -> float:
        """Estimate a stable y range without being dominated by outliers."""
        finite = data[np.isfinite(data)]
        if finite.size == 0:
            return 1.0
        centered = finite - np.nanmedian(finite)
        scale = np.nanpercentile(np.abs(centered), 98) * 1.3
        if not np.isfinite(scale) or scale <= 0:
            scale = max(1.0, float(np.nanmax(np.abs(finite))))
        return max(scale, 1e-6)

    def _ensure_line_count(self, count: int) -> None:
        """Ensure enough persistent line visuals exist for the requested plot."""
        while len(self.lines) < count:
            self.lines.append(scene.visuals.Line(parent=self.view.scene))

    def _clear_line(self, line: object) -> None:
        """Clear a VisPy line without leaving it with empty bounds."""
        line.set_data(pos=EMPTY_LINE_POINTS, color=(0.0, 0.0, 0.0, 0.0), width=1.0)

    def _ensure_channel_labels(self, count: int) -> None:
        """Ensure all-channel mode has one text label per channel."""
        while len(self.channel_labels) < count:
            self.channel_labels.append(
                scene.Text(
                    text="",
                    color="#202124",
                    font_size=8,
                    anchor_x="right",
                    anchor_y="center",
                    parent=self.view.scene,
                )
            )
        for label in self.channel_labels[count:]:
            label.visible = False

    def _ensure_time_label_count(self, count: int) -> None:
        while len(self.time_texts) < count:
            self.time_texts.append(
                scene.Text(
                    text="",
                    color="#202124",
                    font_size=10,
                    anchor_x="center",
                    anchor_y="top",
                    parent=self.view.scene,
                )
            )

    def _adaptive_time_tick_step(self) -> float:
        candidates = (1.0, 2.0, 5.0, 10.0, 15.0, 20.0, 30.0)
        target_step = self.visible_duration_seconds / 6.0
        for candidate in candidates:
            if candidate >= target_step:
                return candidate
        return candidates[-1]

    def _plot_x_min(self) -> float:
        return -self.visible_duration_seconds * self.left_margin_fraction

    def _y_axis_label_x(self) -> float:
        return self._plot_x_min() * 0.82

    def _y_tick_label_x(self) -> float:
        return -self.visible_duration_seconds * 0.035

    def _channel_label_x(self) -> float:
        return self._y_tick_label_x()

    def _below_x_axis_positions(self, y_min: float, y_max: float) -> tuple[float, float]:
        y_span = max(1.0, y_max - y_min)
        time_label_y = y_min - max(0.28, y_span * 0.045)
        axis_label_y = y_min - max(0.48, y_span * 0.085)
        return time_label_y, axis_label_y

    def _bottom_padding(self, y_min: float, y_max: float) -> float:
        return max(0.1, (y_max - y_min) * 0.02)

    def _hide_channel_labels(self) -> None:
        for label in self.channel_labels:
            label.visible = False

    def _update_minimum_height(self, channel_count: int) -> None:
        """Resize the live canvas so the requested channel count fits the viewport."""
        if self.visible_channel_limit is None or channel_count <= self.visible_channel_limit:
            minimum_height = self.minimum_plot_height
        else:
            minimum_height = max(
                self.minimum_plot_height,
                math.floor(channel_count * self.viewport_height / self.visible_channel_limit),
            )
        self.canvas.native.setMinimumHeight(minimum_height)
        self.setMinimumHeight(minimum_height)


class AllChannelsDialog(QDialog):
    """Dialog showing the live all-channel overview.

    MainView owns the dialog and redraws its embedded VisPySignalPlot from the
    latest cached live data whenever the user opens "Plot All Channels".
    """

    def __init__(self, plot: VisPySignalPlot, parent: QWidget | None = None) -> None:
        """Wrap an existing VisPySignalPlot in a top-level dialog window."""
        super().__init__(parent)
        self.setWindowTitle(button_labels.PLOT_ALL_CHANNELS_DIALOG_TITLE)
        self.resize(1100, 760)
        layout = QVBoxLayout(self)
        layout.addWidget(plot)


class OfflineMatplotlibPlot(QWidget):
    """Offline Matplotlib plot for worker-prepared recorded channels.

    MainView keeps this widget on the GUI thread. OfflineProcessingWorker
    prepares the selected/sliced/downsampled arrays, and MainView passes that
    payload into ``plot_prepared`` for final rendering.
    """

    def __init__(self, parent: QWidget | None = None) -> None:
        """Create the Matplotlib figure canvas used by the Offline tab."""
        super().__init__(parent)
        self.sample_rate = 1000.0
        self.selected_channel = 0
        self.visible_duration_seconds: float | None = None
        self.visible_window_start_seconds = 0.0
        self.recording_duration_seconds = 0.0
        self.visible_channel_limit: int | None = 4
        self.minimum_plot_height = 380
        self.viewport_height = self.minimum_plot_height
        self._plotted_channel_count = 0

        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        self.figure = Figure(figsize=(7, 4), tight_layout=False)
        self.canvas = FigureCanvas(self.figure)
        self.axes = self.figure.add_subplot(111)
        layout.addWidget(self.canvas)
        self.show_empty(button_labels.OFFLINE_NO_RECORDING_MESSAGE)

    def set_visible_channel_limit(self, limit: int | None) -> None:
        """Set how many subplots should fit before the offline plot scrolls."""
        self.visible_channel_limit = limit
        self._update_minimum_height(self._plotted_channel_count)

    def set_visible_duration_seconds(self, seconds: float | None) -> None:
        """Set how many seconds of recorded data are shown."""
        self.visible_duration_seconds = None if seconds is None else max(0.5, float(seconds))

    def set_visible_window_start_seconds(self, seconds: float) -> None:
        """Set the start of the offline inspection window."""
        self.visible_window_start_seconds = max(0.0, float(seconds))
        self.update_visible_x_range()

    def set_visible_channel_viewport_height(self, height: int) -> None:
        """Use the scroll viewport height to keep the chosen number visible."""
        self.viewport_height = max(self.minimum_plot_height, int(height))
        self._update_minimum_height(self._plotted_channel_count)

    def set_channel(self, channel_index: int) -> None:
        """Remember the last selected channel for legacy single-channel calls."""
        self.selected_channel = channel_index

    def plot(
        self,
        data: np.ndarray,
        mode: str,
        channel_indices: list[int] | None = None,
    ) -> None:
        data = np.asarray(data, dtype=np.float64)
        if data.size == 0 or data.ndim != 2 or data.shape[1] == 0:
            self.show_empty(button_labels.OFFLINE_NO_RECORDED_DATA_AVAILABLE_MESSAGE)
            return

        if channel_indices is None:
            channel_indices = [self.selected_channel]

        valid_indices = [
            channel_index
            for channel_index in channel_indices
            if 0 <= channel_index < data.shape[0]
        ]
        self._plotted_channel_count = len(valid_indices)
        if not valid_indices:
            self.show_empty(button_labels.OFFLINE_SELECT_CHANNELS_MESSAGE)
            return

        self._update_minimum_height(len(valid_indices))
        self.recording_duration_seconds = data.shape[1] / self.sample_rate
        if self.visible_duration_seconds is None:
            start_sample = 0
            end_sample = data.shape[1]
        else:
            max_visible_samples = max(2, int(self.visible_duration_seconds * self.sample_rate))
            max_start_sample = max(0, data.shape[1] - max_visible_samples)
            start_sample = min(
                max_start_sample,
                int(self.visible_window_start_seconds * self.sample_rate),
            )
            end_sample = min(data.shape[1], start_sample + max_visible_samples)

        visible_data = data[:, start_sample:end_sample]
        x_values = np.arange(start_sample, end_sample, dtype=np.float64) / self.sample_rate
        self.figure.clear()
        axes = self.figure.subplots(len(valid_indices), 1, sharex=True, squeeze=False).ravel()

        for axis, channel_index in zip(axes, valid_indices):
            axis.plot(
                x_values,
                visible_data[channel_index],
                color=channel_color_css(channel_index),
                linewidth=0.9,
            )
            axis.set_ylabel(f"Ch {channel_index + 1}\nµV")
            axis.grid(True, alpha=0.25)

        axes[0].set_title(f"Recorded Channels - {mode}")
        axes[-1].set_xlabel("Time (s)")
        self.axes = axes[0]
        self.canvas.draw_idle()

    def plot_prepared(
        self,
        data: np.ndarray,
        x_values: np.ndarray,
        mode: str,
        channel_indices: list[int],
        recording_duration_seconds: float,
    ) -> None:
        """Draw worker-prepared offline data without extra processing.

        ``data`` is already filtered/sliced/downsampled by OfflineProcessingWorker.
        This method only updates Qt/Matplotlib objects, so it must be called
        from MainView on the GUI thread.
        """
        data = np.asarray(data, dtype=np.float64)
        x_values = np.asarray(x_values, dtype=np.float64)
        self.recording_duration_seconds = max(0.0, float(recording_duration_seconds))
        self._plotted_channel_count = len(channel_indices)

        if data.size == 0 or data.ndim != 2 or data.shape[1] == 0 or not channel_indices:
            self.show_empty(button_labels.OFFLINE_SELECT_CHANNELS_MESSAGE)
            return

        self._update_minimum_height(len(channel_indices))
        self._plot_stacked_prepared(data, x_values, mode, channel_indices)

    def _plot_stacked_prepared(
        self,
        data: np.ndarray,
        x_values: np.ndarray,
        mode: str,
        channel_indices: list[int],
    ) -> None:
        """Draw many offline channels on one axes to keep scrolling responsive."""
        self.figure.clear()
        self.figure.subplots_adjust(left=0.08, right=0.995, top=0.92, bottom=0.1)
        axis = self.figure.add_subplot(111)
        row_spacing = 3.0
        offsets = np.arange(len(channel_indices) - 1, -1, -1, dtype=np.float64) * row_spacing

        for row_index, channel_index in enumerate(channel_indices):
            row = data[row_index]
            centered = row - np.nanmedian(row)
            scale = np.nanpercentile(np.abs(centered), 95)
            if not np.isfinite(scale) or scale <= 0:
                scale = 1.0
            axis.plot(
                x_values,
                centered / scale + offsets[row_index],
                color=channel_color_css(channel_index),
                linewidth=0.8,
            )

        axis.set_title(f"Recorded Channels - {mode}")
        axis.set_xlabel("Time (s)")
        axis.set_ylabel("Channels")
        axis.set_yticks(offsets)
        axis.set_yticklabels([f"Ch {channel_index + 1}" for channel_index in channel_indices])
        axis.set_ylim(offsets[-1] - 1.6, offsets[0] + 1.6)
        axis.grid(True, axis="x", alpha=0.25)
        self.axes = axis
        self.update_visible_x_range(redraw=False)
        self.canvas.draw_idle()

    def update_visible_x_range(self, redraw: bool = True) -> None:
        """Move the displayed offline time window without rebuilding the plot."""
        if self.axes is None or not self.axes.has_data():
            return
        if self.visible_duration_seconds is None:
            self.axes.set_xlim(0.0, max(1.0, self.recording_duration_seconds))
        else:
            start = self.visible_window_start_seconds
            self.axes.set_xlim(start, start + self.visible_duration_seconds)
        if redraw:
            self.canvas.draw_idle()

    def show_empty(self, message: str) -> None:
        """Display a centered empty-state message in the Offline tab plot."""
        self._plotted_channel_count = 0
        self._update_minimum_height(0)
        self.figure.clear()
        self.axes = self.figure.add_subplot(111)
        self.axes.text(0.5, 0.5, message, ha="center", va="center")
        self.axes.set_axis_off()
        self.canvas.draw_idle()

    def _update_minimum_height(self, channel_count: int) -> None:
        """Resize the offline canvas so the selected visible-channel count fits."""
        if self.visible_channel_limit is None or channel_count <= self.visible_channel_limit:
            minimum_height = self.minimum_plot_height
        else:
            minimum_height = max(
                self.minimum_plot_height,
                math.floor(channel_count * self.viewport_height / self.visible_channel_limit),
            )
        self.canvas.setMinimumHeight(minimum_height)
        self.setMinimumHeight(minimum_height)
